print("Welcome to the Greeting Application.")
print("This application will greet the customers.")
print("The owner of this application is Transcend Team.")
print("This app will be the main revenue source for the company.")
print("We need to monitor this app properly")
